
platform :ios, '14.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Texture'

end

# --------------------------------------------------------
# Post-install hook to set for all pods min deployment target to at least iOS 14
# Otherwise we can get errors in Xcode for pods using iOS 9 like Texture. This is because Xcode   does not support those old iOS versions anymore
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force all pods (including Texture) to use iOS 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end